---
title: ''
  html_document:
    df_print: paged
---

\newpage

# `r fontawesome::fa("calendar-alt")` Class schedule. 

IF, Spring 2023. Room 1401, 19:00 – 22:00.

## Part 1. `r fontawesome::fa("battery-quarter")`

**Session 1. `r fontawesome::fa("handshake")` Thursday, 12 January.**

- Reading. Course syllabus (this document).
- Activity. Welcome and introduction to the course.
- Activity. Set up your free DataCamp and Deepnote accounts, you should have invitations in your UDEM student email.
- Activity. Define your group of no more than 4 members, you should have an invitation in your UDEM student email.
- Register and attend the following DataCamp webinar. [Exploratory data analysis in R for absolute beginners.](https://www.datacamp.com/webinars/data-analysis-r-beginners)
- Reading. @Hull9, Chapter 10 *Mechanics of options markets*.
- Reading. @lozanoIF, Chapter 1 *Options*.
- Complementary material. Video: [Mechanics of options markets.](https://youtu.be/z7P2bMCovf0)
- Complementary material. @brealey2020principles, Chapter 20 *Understanding options*.

**Session 2. Thursday, 19 January.**

- Reading. @Hull9, Chapter 12 *Trading strategies involving options*. 
- Reading. @lozanoIF, Chapter 1 *Options*.
- Complementary material. PowerPoint slides: [John C. Hull.](https://www-2.rotman.utoronto.ca/~hull/ofodslides/index.html)

**Session 3. Thursday, 26 January.**

- Reading. @Hull9, Chapter 12 *Trading strategies involving options*. 
- Activity. $H_1$ review.
- Extra marks. DataCamp skill track: *Applied finance in R*. Before 10:00 a.m.


**Session 4, Zoom. Thursday, 2 February.**

- Super extra marks. Individual class activity. DataCamp assessment: *R programming*.
- Extra marks. $ME_1$ instructions in Blackboard.
- Graded. Complete $H_1$ before 10:00 a.m.
- Activity. Review $H_1$ answers.
- Activity. $E_1$ review.

**Session 5, Zoom. `r fontawesome::fa("heart")` Thursday, 9 February.**

- Graded. $E_1$ instructions in Blackboard.
- Activity. Review $E_1$ answers.
- Extra marks. The wheel of fortune 1/3.

## Part 2. `r fontawesome::fa("battery-half")`

**Session 6. Thursday, 16 February.**

- Reading. @Hull9, Chapter 11 *Properties of stock options*. 
- Reading. @lozanoIF, Chapter 2 *Options properties*.
- Complementary material. Video: [Basics of derivative pricing and valuation.](https://youtu.be/NdX7vDIUVQg)
- Complementary material. @brealey2020principles, Chapter 20 *Understanding options*.
- Graded. Submit $H_1$ and $E_1$ auto and co-evaluation before 10:00 a.m. Instructions in Blackboard.
- Extra marks. DataCamp skill track: *Shiny fundamentals with R*. Before 10:00 a.m.

**Session 7. Thursday, 23 February.**

- Reading. @Hull9, Chapter 11 *Properties of stock options*. 
- Reading. @lozanoIF, Chapter 2 *Options properties*.

**Session 8. `r fontawesome::fa("female")` Thursday, 2 March.**

- Reading. @Hull9, Chapter 13 *Binomial trees*. 
- Reading. @lozanoIF, Chapter 3 *Binomial trees*.
- Complementary material. Video: [Binomial option pricing model.](https://youtu.be/7hL_4J5VjRw)
- Activity. $H_2$ review.
- Extra marks. [Open online course on gender and environment.](https://unccelearn.org/course/view.php?id=39&page=overview) Submit your PDF certificate before 10:00 a.m. by the discussion forum.

**Session 9, Zoom. $\pi$ Thursday, 9 March.**

- Super extra marks. Individual class activity. DataCamp assessment: *Data visualization with R*.
- Extra marks. $ME_2$ instructions in Blackboard.
- Graded. Complete $H_2$ before 10:00 a.m.
- Activity. Review $H_2$ answers.
- Activity. $E_2$ review.

**Session 10, Zoom. Thursday, 16 March.**

- Graded. $E_2$ instructions in Blackboard.
- Review $E_2$ answers.
- Extra marks. The wheel of fortune 2/3.

## Part 3. `r fontawesome::fa("battery-three-quarters")`

**Session 11. Thursday, 23 March.**

- Reading. @Hull9, Chapter 14 *Wiener Processes and Itô's lemma*. 
- Reading. @lozanoIF, Chapter 4 *Wiener processes*.
- Complementary material. Blog entry: [Brownian motion in financial markets.](https://www.cantorsparadise.com/brownian-motion-in-financial-markets-ea5f02204b14)
- Graded. Submit $H_2$ and $E_2$ auto and co-evaluation before 10:00 a.m. Instructions in Blackboard.
- Extra marks. DataCamp skill track: *Big data with R*. Before 10:00 a.m.
- Mention DataCamp in social media if possible. [Instructions.](https://docs.google.com/document/d/1Dv-L036CZWsZCmn9W5p0ikgetlc4GcT-NQ9Rp_HebE0/edit)

**Session 12. Thursday, 30 March.**

- Reading. @Hull9, Chapter 15 *The Black–Scholes–Merton model*.
- Complementary material. Videos: First [Introduction to the Black-Scholes formula.](https://youtu.be/pr-u4LCFYEY) Second [How to interpret $N(d_1)$ and $N(d_2)$ in Black Scholes Merton.](https://youtu.be/spkim5Ns304)

**Holiday. `r fontawesome::fa("umbrella-beach")` Thursday, 6 April.**

**Session 13. Thursday, 13 April.**

- Reading. @Hull9, Chapter 22 *Value at Risk (sections 22.1 to 22.4)*.
- Reading. @lozanoIF, Chapter 5 *VaR*.
- Extra marks. [Introduction to green economy.](https://unccelearn.org/course/view.php?id=51&page=overview) Submit your PDF certificate before 10:00 a.m. by the discussion forum.

**Session 14. Thursday, 20 April.**

- Reading. @Hull9, Section 23.8 *Estimating volatilities and correlations*. 
- Reading. @lozanoIF, Chapter 5 *VaR*.
- Complementary material. @brealey2020principles, Chapter 8 *Portfolio theory and the capital asset pricing model*.
- To know more about portfolio selection see @ruppert2011statistics, Chapters 16.
- Extra marks. DataCamp skill track: *Intermediate tidyverse toolbox*. Before 10:00 a.m.

**Session 15, Zoom. `r fontawesome::fa("children")` Thursday, 27 April.**

- Extra marks. $ME_F$ instructions in Blackboard.

**Session 16. `r fontawesome::fa("jedi-order")` Thursday, 4 May.**

- Complete $H_3$ before 10:00 a.m.
- Activity. $E_F$ review.
- Extra marks. The wheel of fortune 3/3.
- Farewell.

**Session 17, Zoom. Friday, 12 May, 16:00 – 19:00.**

- Activity. Open rehearsal PEF students.

## The end. `r fontawesome::fa("battery-full")`

**Final exam, Zoom. Saturday, 20 May, 13:00 – 15:00.**

- Graded. $E_F$ instructions in Blackboard.


\newpage