---
title: ''
  html_document:
    df_print: paged
---

\newpage

# `r fontawesome::fa("calendar-alt")` Class schedule. 

IF, Fall 2023. Room 1307, 19:00 – 22:00.

## `r fontawesome::fa("battery-quarter")` Part 1.

**Session 1. `r fontawesome::fa("handshake")` Monday, 7 August.**

- Reading. Course syllabus (this document).
- Activity. Welcome and introduction to the course.
- Activity. Set up your free DataCamp and Deepnote accounts. You should have received invitations in your UDEM student email.
- Activity. Define your group of no more than 4 members. You should have received an invitation in your UDEM student email.
- Reading. @Hull9, Chapter 10 *Mechanics of options markets*.
- Reading. @lozanoIF, Chapter 1 *Payoff functions*.
- Complementary material. Video: [Mechanics of options markets.](https://youtu.be/z7P2bMCovf0)
- Complementary material. @brealey2020principles, Chapter 20 *Understanding options*.

**Session 2. Monday, 14 August.**

- Reading. @Hull9, Chapter 12 *Trading strategies involving options*. 
- Reading. @lozanoIF, Chapter 1 *Payoff functions*.
- Complementary material. PowerPoint slides: [John C. Hull.](https://www-2.rotman.utoronto.ca/~hull/ofodslides/index.html)
- Extra marks 1/8. DataCamp skill track: *Big Data with R*, before 7:00 a.m.

**Session 3. Monday, 21 August.**

- Reading. @Hull9, Chapter 12 *Trading strategies involving options*. 
- Activity. $H_1$ review.
- Extra marks 2/8. DataCamp skill track: *Finance Fundamentals in Python*, before 7:00 a.m.

**Session 4, Zoom. Monday, 28 August.**

- Extra marks. $ME_1$ instructions in Blackboard.
- Graded. Complete $H_1$ before 7:00 a.m.
- Activity. Discuss $H_1$ answers.
- Extra marks. Mentimeter 1/3.
- Activity. $E_1$ review.

**Session 5, Zoom. Monday, 4 September.**

- Graded. $E_1$ Instructions in Blackboard.
- Activity. Discuss $E_1$ answers.
- Extra marks. The wheel of fortune 1/3.

## `r fontawesome::fa("battery-half")` Part 2.

**Session 6. Monday, 11 September.**

- Reading. @Hull9, Chapter 11 *Properties of stock options*. 
- Reading. @lozanoIF, Chapter 2 *Options properties*.
- Complementary material. Video: [Basics of derivative pricing and valuation.](https://youtu.be/NdX7vDIUVQg)
- Complementary material. @brealey2020principles, Chapter 20 *Understanding options*.
- Graded. Submit $H_1$ and $E_1$ auto and co-evaluation before 7:00 a.m. Instructions in Blackboard.
- Extra marks 3/8. [Plastic Waste and the Basel Convention.](https://unccelearn.org/course/view.php?id=131&page=overview) Submit your PDF certificate before 7:00 a.m. by the discussion forum.

**Session 7. Monday, 18 September.**

- Reading. @Hull9, Chapter 11 *Properties of stock options*. 
- Reading. @lozanoIF, Chapter 2 *Options properties*.
- Extra marks 4/8. DataCamp skill track: *Applied Finance in Python*, before 7:00 a.m.

**Session 8. Monday, 25 September.**

- Reading. @Hull9, Chapter 13 *Binomial trees*. 
- Reading. @lozanoIF, Chapter 3 *Binomial trees*.
- Complementary material. Video: [Binomial option pricing model.](https://youtu.be/7hL_4J5VjRw)
- Activity. $H_2$ review.
- Extra marks 5/8. DataCamp skill track: *Big Data with PySpark*, before 7:00 a.m.

**Session 9, Zoom. Monday, 2 October.**

- Extra marks. $ME_2$ instructions in Blackboard.
- Graded. Complete $H_2$ before 7:00 a.m.
- Activity. Discuss $H_2$ answers.
- Extra marks. Mentimeter 2/3.
- Activity. $E_2$ review.

**Session 10, Zoom. Monday, 9 October.**

- Graded. $E_2$ Instructions in Blackboard.
- Activity. Discuss $E_2$ answers.
- Extra marks. The wheel of fortune 2/3.

## `r fontawesome::fa("battery-three-quarters")` Part 3.

**Session 11. Monday, 16 October.**

- Reading. @Hull9, Chapter 14 *Wiener Processes and Itô's lemma*. 
- Reading. @lozanoIF, Chapter 4 *Wiener processes*.
- Complementary material. Blog entry: [Brownian motion in financial markets.](https://www.cantorsparadise.com/brownian-motion-in-financial-markets-ea5f02204b14)
- Graded. Submit $H_2$ and $E_2$ auto and co-evaluation before 7:00 a.m. Instructions in Blackboard.
- Non graded. Mention DataCamp in social media if possible. [Instructions.](https://docs.google.com/document/d/1Dv-L036CZWsZCmn9W5p0ikgetlc4GcT-NQ9Rp_HebE0/edit)
- Extra marks 6/8. [Food Waste Prevention.](https://unccelearn.org/course/view.php?id=129&page=overview) Submit your PDF certificate before 7:00 a.m. by the discussion forum.

**Session 12. Monday, 23 October.**

- Reading. @Hull9, Chapter 15 *The Black–Scholes–Merton model*.
- Complementary material. Videos: First [Introduction to the Black-Scholes formula.](https://youtu.be/pr-u4LCFYEY) Second [How to interpret $N(d_1)$ and $N(d_2)$ in Black Scholes Merton.](https://youtu.be/spkim5Ns304)

**Session 13. Monday, 30 October.**

- Reading. @Hull9, Chapter 22 *Value at Risk (sections 22.1 to 22.4)*.
- Reading. @lozanoIF, Chapter 5 *Value at Risk*.
- Extra marks 7/8. DataCamp skill track: *Natural Language Processing in Python*, before 7:00 a.m.

**Session 14, Zoom. Monday, 6 November.**

- Reading. @Hull9, Section 23.8 *Estimating volatilities and correlations*. 
- Reading. @lozanoIF, Chapter 5 *Value at Risk*.
- Complementary material. @brealey2020principles, Chapter 8 *Portfolio theory and the capital asset pricing model*.
- To know more about portfolio selection see @ruppert2011statistics, Chapters 16.
- Extra marks 8/8. DataCamp skill track: *SQL for Business Analysts*, before 7:00 a.m.
- Extra marks. Mentimeter 3/3.

**Session 15, Zoom. Monday, 13 November.**

- Extra marks. $ME_F$ instructions in Blackboard.
- Non graded. Complete $H_3$ before 7:00 a.m.
- Activity. $E_F$ review.
- Extra marks. The wheel of fortune 3/3.
- Farewell.

**Session 16, Zoom. Tuesday, 21 November.**

- Review.

## `r fontawesome::fa("battery-full")` The end.

**Final exam, Zoom. Monday, 27 November, 19:00 – 21:00.**

- Graded. $E_F$ Instructions in Blackboard.

\newpage
