---
title: Ingeniería financiera (IF). `r fontawesome::fa("cogs")` 
subtitle: Course syllabus. Spring 2023.
author: Dr. Martín Lozano. `r fontawesome::fa("envelope")` <tt>`<martin.lozano@udem.edu>`</tt>
#- name: Back to main [`r fontawesome::fa("home")`](https://mlozanoqf.github.io/)
#  affiliation: Academic website. [Web.](https://sites.google.com/site/mlozanoqf/)
date: Current `r fontawesome::fa("code-commit") ` `r format(Sys.time(), '%d %b %Y, %H:%M:%S.')`
#  bookdown::gitbook: default
output: 
  bookdown::html_document2:
    toc: yes
    toc_float: yes
    toc_depth: 2
    number_sections: yes
    fig_caption: yes
    code_folding: show
    theme: readable #darkly 
    includes:
      after_body: analytics_if.html
abstract: A course syllabus is an academic document with relevant information for students. This document represents your ultimate guide to the successful completion of this course. Please read it regularly and carefully. Here, you will find a comprehensive description of the course goals, rules, objectives, recommendations, grading details, a detailed schedule, activities, resources, references and learning outcomes. The objective of this document is to give you full certainty about what to expect from this course starting from day 1 until the final exam. In my experience, reading this syllabus is positively related with the student's performance.

bibliography: mybibfile.bib
---

```{=tex}
\newpage 
\hypersetup{linkcolor=black}
\renewcommand*\contentsname{Index.}
\tableofcontents
```

```{r include=FALSE}
# This removes all items in environment. 
# It is a good practice to start your code this way.
rm(list=ls())
library(fontawesome)
library(vembedr)
library(tictoc)
tic()
```

```{r global_options, include = FALSE}
knitr::opts_chunk$set(warning = FALSE, message = FALSE)
knitr::opts_chunk$set(fig.pos = "H", out.extra = "")
```

```{r, xaringanExtra-clipboard, echo=FALSE}
htmltools::tagList(
  xaringanExtra::use_clipboard(
    button_text = "<i class=\"fa fa-clone fa-2x\" style=\"color: #301e64\"></i>",
    success_text = "<i class=\"fa fa-check fa-2x\" style=\"color: #90BE6D\"></i>",
    error_text = "<i class=\"fa fa-times fa-2x\" style=\"color: #F94144\"></i>"
  ),
  rmarkdown::html_dependency_font_awesome()
)
```

````{=html}
```{r, echo=FALSE, results='asis'}
xfun::file_string('contact.html')
```
````

# [`r fa("arrow-circle-up", fill = "black")`](https://mlozanoqf.github.io/ARF1/) [<span style="color: black">Back to top.</span>](https://mlozanoqf.github.io/ARF1/) {-}

\newpage

```{r introduction, child = 'Introduction.Rmd'}
```

<!-- \newpage -->

<!-- ```{r overview, child = 'Course overview.Rmd'} -->
<!-- ``` -->

<!-- \newpage -->

<!-- ```{r data science, child = 'Data Science.Rmd'} -->
<!-- ``` -->

<!-- \newpage -->

<!-- ```{r resources and activities, child = 'Learning resources and activities.Rmd'} -->
<!-- ``` -->

<!-- \newpage -->

<!-- ```{r evaluation, child = 'Evaluation.Rmd'} -->
<!-- ``` -->

<!-- \newpage -->

<!-- ```{r check, child = 'Checklist.Rmd'} -->
<!-- ``` -->

<!-- <!-- \newpage --> -->

<!-- <!-- ```{r schedule, child = 'Class schedule.Rmd'} --> -->
<!-- <!-- ``` --> -->

<!-- \newpage -->

<!-- ```{r resources, child = 'Internet resources.Rmd'} -->
<!-- ``` -->

```{r include=FALSE}
a <- toc()
```

This document took `r round(as.numeric((a$toc-a$tic)), 2)` seconds to compile in Rmarkdown, `r R.version.string`.

# `r fontawesome::fa("book-open")` References.