---
title: ''
  html_document:
    df_print: paged
---

\newpage

# `r fontawesome::fa("globe")` Internet resources.

The amount of free online resources and references to learn R, and its applications in  finance and economics is huge. This list is constantly growing.

## Learn `r fontawesome::fa("r-project")`.

Consider the following specific online and free resources to start or continue learning R.

- As my student you have a free DataCamp account. You can find at least 151 courses and 45 projects about R.
- [LearnR](https://learnr.numbat.space/). An interactive introduction to data analysis with R. In this course, you'll learn the basics of using R for data analysis. This should provide you with the necessary skills to use R when learning more advanced and specialised topics. You don't need any prior experience with R, statistics, or programming to work through this material, however if you already have some experience you can start from any chapter you'd like to learn from. 
- [Swirl](https://swirlstats.com/) teaches you R programming and data science interactively, at your own pace, and right in the R console. 
- [Interactive Tutorials for R.](https://rstudio.github.io/learnr/) The <tt>`learnr`</tt> package makes it easy to turn any R Markdown document into an interactive tutorial. 
- R for Dummies. @de2015r.
- Introduction to Econometrics with R. @hanck2020introduction.
- Introduction to Econometrics with R. @Oswaldeconometrics.
- Using R for Introductory Econometrics. @heiss2020usingR.
- Handbook of Regression Modeling in People Analytics. With Examples in R and Python. @mcnulty2021handbook.
- R Programming for Data Science. @peng2016r.
- <tt>`ggplot`</tt>: elegant graphics for data analysis. @wickham2016ggplot2.
- Bookdown: Authoring Books and Technical Documents with R Markdown. @xie2021bookdown.
- R Markdown Cookbook. @xie2020r.
- R markdown: The Definitive Guide. @xie2021r.
- R for Data Science. @grolemund2018r.
- To understand how R Markdown works: [R Markdown guidelines.](https://crd150.github.io/hw_guidelines.html)
- Thiyanga Talagala: [A detailed R Markdown guide.](https://talks-thiyanga.netlify.app/rmarkdown_rladies/rmarkdownrladies_tst#1)
- Let’s Git started. @bryan2018happy.
- Probability, Statistics, and Data: A fresh approach using R. [Foundations of Statistics with R.](https://mathstat.slu.edu/~speegle/_book/)


## YouTube installation guides.

In principle, as we are using Deepnote, you do not need to install any software on your computer. However, you may be interested to work with R on your local computer. Here is a good list of YouTube installation guides to do so. 

As you may understand, R and RStudio versions are frequently updated and people regularly upload installation guides on YouTube. If you find a newer video for installing a newer version please share. In any case, these videos can definitely help you as a guide to install the newer version available.

-   [Download & Install R 3.6.3](https://youtu.be/3OxPMYP8lNU)
-   [Download & Install RStudio Desktop 1.3.959](https://youtu.be/uvnuQ_fKrMc)
-   [Installing R and Rstudio on MacOS.](https://youtu.be/Y20P3u3c_1c)
-   [Orientation and Setting up R (Setting up R)](https://www.youtube.com/watch?v=y2wgdw5_MZg&t=2498s)
-   [Orientation and Setting up R (Setting up RStudio)](https://www.youtube.com/watch?v=y2wgdw5_MZg&t=3002s)
-   [RStudio: A Guided Tour (by Jamison Crawford).](https://youtu.be/xgPwDlAtuNI)
-   [How to Install RStudio (and Knit to PDF).](https://youtu.be/2Sovzf6lVRo)
-   [RStudio: Explaining the Interface & R Markdown.](https://youtu.be/AHAR7j-IUOw)
-   [How to Connect RStudio with Git (Github) for Cloning and Pushing Repo.](https://youtu.be/lXwH2R4n3RQ)

<!-- ## RStudio and GitHub integration plus pull request (PR). -->

<!-- GitHub is a website and cloud-based service that helps developers store and manage their code, as well as track and control changes to their code and projects. GitHub is one of the world's largest communities of open source code developers. It fosters collaboration and communication between developers similar to a social network of coders. Here, we assume you have installed R, RStudio, Git, and you have a GitHub account. This series of videos are good to understand the basics of how professionals develop code in a collaborative way. -->

<!-- **Video 1 of 4.** I recommend you to start at minute 10. Before minute 10 you can see an installation process, but there are better videos in the previous section (YouTube installation guides). Starting from minute 10 you can learn how to link RStudio with your GitHub account using the SSH RSA key which I highly recommend. You may find Samsun's voice speed a bit slow, just remember you can change the playback speed in YouTube if necessary. [Installing R, R Studio, and link R Studio with Github account - Part 4 - by Samsun.](https://youtu.be/-LKFxtaU5bY) -->

<!-- **Video 2 of 4.** The relevant part starts at minute 5:50. In the first part Lisa explains how to use the `{usethis}` library to link RStudio with your GitHub account, but I recommend you to follow the video 1 for that purpose. So, please watch this from minute 5:50 to the end. There is one more thing, in 8:39 she clones with HTTPS, but I recommend you cloning with SSH, the option to select SSH is just right there in the same window. In my experience, cloning with SSH is better because of security issues and because you may not be asked to log in repeatedly. [Using git and GitHub in R Studio.](https://youtu.be/QLFc9gw_Hfs) -->

<!-- **Video 3 of 4.** Video 2 explained RStudio and GitHub integration to work alone. This video 3 explains how to work with others as collaborators (Lisa and Heather). In the context of this class, your classmate colleagues are collaborators, I am not included as a collaborator. Note that Lisa and Heather cloned with HTTPS but I recommend cloning with SSH. They show how to work with branches and pull request between collaborators. Starting from 30:40 the tutorial is somewhat less interesting, you are free to look at it, but it is not vital for our purposes. [Using Git and GitHub in R (second part).](https://youtu.be/megZYkCLMA4) -->

<!-- **Video 4 of 4.** Layla explains very well how to interact between a team of students and your professor or instructor. Note that her RStudio panes are in a very weird location but I guess you still can follow. Layla also recommends working with branches, this is a good practice. She also knits in html but I will ask you to knit in pdf most of the time. Note that she actually takes the side of the students who are interacting with an instructor which is called reviewer in GitHub. [Branching and Committing from RStudio and creating a PR on GitHub.](https://youtu.be/4Jjk_43g9xU) -->

<!-- **Complementary video.** This is in Spanish, it is a good video, but the previous 4 are somewhat better. She links RStudio and GitHub using the terminal, I normally follow the procedure in the first video (Samsun's video). She also clones with HTTPS, but I recommend you cloning with SSH as I explained before. [RStudio y GitHub: control de versiones. ](https://youtu.be/Xy_CLr7htfA) -->

## Software.

Main technology used in this course.

-   [The R Project for Statistical Computing.](https://www.r-project.org/) R is a free software environment for statistical computing and graphics. It compiles and runs on a wide variety of UNIX platforms, Windows and MacOS. 
-   [RStudio.](https://posit.co/) Inspired by innovators in science, education, government, and industry, RStudio develops free and open tools for R, and enterprise-ready professional products for teams who use both R and Python, to scale and share their work. 
-   [DataCamp.](https://www.datacamp.com/) Learn the data skills you need online at your own pace—from non-coding essentials to data science and machine learning. 
-   [Tiny$\TeX{}$.](https://yihui.org/tinytex/) A lightweight, cross-platform, portable, and easy-to-maintain $\LaTeX{}$ distribution based on $\TeX{}$ Live. 
-   [Compile R online.](https://rextester.com/l/r_online_compiler)
-   [$\LaTeX{}$ base.](https://latexbase.com) A web-based $\LaTeX{}$ editor with live document preview. 
-   [Overleaf.](https://www.overleaf.com/) The easy to use, online, collaborative $\LaTeX{}$ editor. 
-   [$\LaTeX{}$.](https://www.latex-project.org/) $\LaTeX{}$ is a high-quality typesetting system; it includes features designed for the production of technical and scientific documentation. 
-   [Git.](https://git-scm.com/) A free and open source distributed version control system designed to handle everything from small to very large projects with speed and efficiency. 
-   [GitHub.](https://github.com/) A provider of Internet hosting for software development and version control using Git. It offers the distributed version control and source code management functionality of Git, plus its own features. 

## Blogs and resources.

Here you can find questions and answers about programming in R.

-   [R-Bloggers](https://www.r-bloggers.com) is a blog aggregator of content contributed by bloggers who write about R (in English). The site helps R bloggers and users to connect and follow the R blogosphere. 
-   [Stack Overflow.](https://stackoverflow.com) Founded in 2008, Stack Overflow’s public platform is used by nearly everyone who codes to learn, share their knowledge, collaborate, and build their careers. 
-   [R and Data Mining.](http://www.rdatamining.com)
-   [Revolutions.](https://blog.revolutionanalytics.com/) Milestones in AI, Machine Learning, Data Science, and visualization with R and Python since 2008. 
-   [R-ladies](https://rladies.org/) is a worldwide organization whose mission is to promote gender diversity in the R community.
-   These sources are the ones that most often hold the data that social science students and researchers at Tufts are looking for. [Social Science Data and Statistics Resources.](https://researchguides.library.tufts.edu/data/r)
-   [Stack Exchange](https://tex.stackexchange.com/) is a question and answer site for users of $\TeX{}$, $\LaTeX{}$, Con$\TeX{}$t, and related typesetting systems. 
-   [Kaggle.](https://www.kaggle.com/) Inside Kaggle you’ll find all the code & data you need to do your data science work. Use over 50,000 public datasets and 400,000 public notebooks to conquer any analysis in no time.
-   A gap exists between the Data Scientist's skillset and the Business Objectives. [Learn Data Science.](https://www.business-science.io/)
-   [Rdatasets](https://vincentarelbundock.github.io/Rdatasets/index.html) A collection of nearly 1500 datasets that were originally distributed alongside the statistical software environment R and some of its add-on packages.

## Others.

-   [ProjectElon.](https://www.youtube.com/c/ProjectElon/) Study Motivation.
-   [iPanda.](https://www.youtube.com/c/iPandaChannel) Pandas are precious and vulnerable species in the world today.  
-   Twitter hashtags: \#rstats, \#DataScience

